config/routes.rb
Rails.application.routes.draw do

 get 'admins/sign_up' => redirect('/404.html')
  devise_for :admins
  root 'students#index'
  
  resources :students

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         password_length: 3..128 
end

app/models/student.rb
class Student < ActiveRecord::Base
	validates :name, presence: true, length: 3..120
	validates :marks, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	before_action :authenticate_admin!, except: [:index]
	before_action :find_student, only: [:edit, :update, :destroy]
  def new
  	@student=Student.new
  end

  def create
  	@student=Student.new(student_params)
  	if @student.save
  		redirect_to root_path, notice: "success"
  	else
  		render :new
  	end
  end

  def edit
  end

  def update
    if@student.update(student_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def index
  	@students=Student.all
  end

  def destroy
  	@student.delete
  	redirect_to @student
  end

  private
  	def student_params
  		params.require(:student).permit(:name, :marks)
  	end

  	def find_student
  		@student=Student.find(params[:id])
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/_links.html.erb
<div class = "nav">
	<% if !admin_signed_in? %>
		<%= link_to "Login", new_admin_session_path %>
	<%else%>
		<%= link_to "Log out",destroy_admin_session_path, method: :delete %>
		<%= link_to "List of Students", students_path%>
		<%= link_to "Add student record", new_student_path%>
	<%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Session163filtersforadmin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class ="wrapper">
	<%= render 'layouts/links'%>
 	<p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class ="content">
		<%= yield %>
	</div>
</div>
</body>
</html>

app/views/students/edit.html.erb
<h1>Edit Student details</h1>

<%= form_for @student do |s|%>
	<%= s.label :name%>:
	<%= s.text_field :name%> <br>

	<%= s.label :marks%>:	
	<%= s.text_field :marks%><br>
	
	<%=s.submit "save"%>
<%end%>

app/views/students/index.html.erb
<h1>List of students</h1>

<table border = 1>
	<tr>
		<th width= 250>Name</th>
		<th width= 180>Marks</th>
		<%if admin_signed_in?%>
			<th width= 100></th>
			<th width= 100></th>
		<%end%>
	</tr>
	<% @students.each do |s|%>
		<tr>
		<td><%=s.name%></td><td align ="center"> <%=s.marks%></td>
		<%if admin_signed_in?%>
		<td><%= link_to "Edit", edit_student_path(s)%></td>
		<td><%= link_to "Delete", s, method: :delete, data: {confirm: "Confirm delete Student record"}%></td>
	</tr>
		<%end%>

		<%end%>
</table>

app/views/students/new.html.erb
<h1>Add Student Record</h1>
<%if @student.errors.any?%>
<ul>
	<%@student.errors.full_messages.each do |msg|%>
		<li><%=msg%></li>
	<%end%>
</ul>
<%end%>

<%= form_for @student do |s|%>
	<%= s.label :name%>
	<%= s.text_field :name%> <br>

	<%= s.label :marks%>
	<%= s.text_field :marks%><br>
	
	<%=s.submit "save"%>
<%end%>